### ISSUE TITLE
 Furnace count reporting including supplemental coils

### ISSUE THREAD

**Issue by mdahlhausen** [NatLabRockies/ComStock#12]
[comstock_sensitivity_reports](https://github.com/NREL/ComStock/blob/main/measures/comstock_sensitivity_reports/measure.rb#L2692-L2749) is treating all gas coils as furnaces (1 gas coil = 1 furnace). Gas coils may be supplemental coils for other kinds of HVAC systems.

The fix is to check whether the coil is the primary heating coil in a unitary system before logging.

**Comment by mpraprost** [comment]
1. comstock_column definitions, comstock_sensitivity_reports - change Furnace to Gas Coil
2. hvac_metadata.csv - change Furnace to Gas Coil
3. comstock_sensitivity_reports - call furnace count columns "primary gas coil", add 2 new columns "supplementary count" and "supplementary capacity total"
