### ISSUE TITLE
Don't forget to `return true` as the end of the run method of measures in the normal path

### ISSUE THREAD

**Issue by jmarrec** [NatLabRockies/ComStock#156]
eg: `return true` missing here:

https://github.com/NREL/ComStock/blob/9cafcc5000f1606ba7025cebe5fd35d648066e2e/resources/measures/set_exterior_lighting_template/measure.rb#L288

This is the root cause of https://unmethours.com/question/98795/unable-to-use-comstock-2024_r1-measures-with-os_sdk-37/

**Comment by eringold** [comment]
This also affects (at least): 
- set_interior_equipment_template
- set_service_water_heating_template
- set_hvac_template
