### ISSUE TITLE
create_bar_from_building_type_ratios OpenStudio3.8.0 test issues

### ISSUE THREAD

**Issue by DavidGoldwasser** [NatLabRockies/ComStock#172]
- [x] #174
`**ERROR MESSAGES**
[openstudio.standards.Geometry.Create] North/South walls don't have the expected area (actual 2,849.4897 ft^2, target 2,449.4897 ft^2)
[openstudio.standards.Geometry.Create] East/West walls don't have the expected area (actual 2,032.9932 ft^2, target 1,632.9932 ft^2)`
(is this new geometry issue in OS, or is there problem with the check in standards). 
- [x] 3x test_two_and_half_stories_individual_sliced (Similar issue for test_rotation_45_party_wall_fraction and test_two_and_half_stories_simple_sliced)
`warning count (0) did not match expectation (1)`
- [x] 3x test_neighboring_buildings In the test assert fails because this is not initialized (similar for test_building_taller_than_neighbors and building_shorter_than_neighbors)
`north_shade = model.getShadingSurfaceByName('North Neighbor Shade')`
These were failing in 3.7.0 and are not currently supported. I altered the test to be shorter, but didn't skip it

- [x] 1x test_preserve_bldg_addl_props  assert(props.featureNames.size == 4)

- [x] test_t24_ofs (something strange with small 2500 sqft 3story building. I will go back and see if this is new to 3.8 or note
`**ERROR MESSAGES**
[openstudio.standards.Geometry.Create] OfS Hall doesn't have the expected floor area (actual 0 ft^2, target 785 ft^2)
[openstudio.standards.Geometry.Create] OfS OfficeSmall doesn't have the expected floor area (actual 2,500 ft^2, target 1,715 ft^2)
[openstudio.standards.Geometry.Create] Sum of actual floor area is 2500.0000000000023 ft^2, sum of target floor area is 2500.0.`

**Comment by DavidGoldwasser** [comment]
Regarding the warnings, I see where it should be happening, but not sure why it isn't
https://github.com/NREL/openstudio-standards/blob/645b55538193ac865ce3d96537f8fd0be473d1ff/lib/openstudio-standards/utilities/logging.rb#L29

**Comment by DavidGoldwasser** [comment]
I can see that `log_messages_to_runner` should bring over warnings
https://github.com/NREL/openstudio-standards/blob/645b55538193ac865ce3d96537f8fd0be473d1ff/lib/openstudio-standards/utilities/logging.rb#L29

This is one of the warnings that should be triggered above
https://github.com/NREL/openstudio-standards/blob/645b55538193ac865ce3d96537f8fd0be473d1ff/lib/openstudio-standards/geometry/create_bar.rb#L1887

Here is what that same measure test looks like in 3.7.0. Note that this test is using single space type which shouldn't be used, that is why it is throwing the crazy warnings. 

**WARNING MESSAGES**
Ignoring perimeter multiplier for bar that represents custom height spaces.
You selected a perimeter multiplier greater than 1.0 but didn't select a bar division method that supports this. The value for this argument will be ignored by the measure
SecondarySchool Auditorium doesn't have the expected floor area (actual 0 ft^2, target 5,040 ft^2)
SecondarySchool Cafeteria doesn't have the expected floor area (actual 0 ft^2, target 3,190 ft^2)
SecondarySchool Classroom doesn't have the expected floor area (actual 0 ft^2, target 30,410 ft^2)
SecondarySchool ComputerRoom doesn't have the expected floor area (actual 0 ft^2, target 4,870 ft^2)
SecondarySchool Corridor doesn't have the expected floor area (actual 0 ft^2, target 21,440 ft^2)
SecondarySchool Gym doesn't have the expected floor area (actual 100,000 ft^2, target 16,460 ft^2)
SecondarySchool Kitchen doesn't have the expected floor area (actual 0 ft^2, target 1,100 ft^2)
SecondarySchool Library doesn't have the expected floor area (actual 0 ft^2, target 4,290 ft^2)
SecondarySchool Lobby doesn't have the expected floor area (actual 0 ft^2, target 2,140 ft^2)
SecondarySchool Mechanical doesn't have the expected floor area (actual 0 ft^2, target 3,490 ft^2)
SecondarySchool Office doesn't have the expected floor area (actual 0 ft^2, target 5,430 ft^2)
SecondarySchool Restroom doesn't have the expected floor area (actual 0 ft^2, target 2,140 ft^2)

So while I was working on geometry issue I changed the OpenStudio::Error to OpenStudio::Warn, and oddly that worked. So think maybe that warning code isn't getting triggered or there is a more localized issue just in some use cases.

-----

- [x] So the reason the warning isn't issued now is because that code isn't triggered. The reason for that is that even though `bldg_type_a` is `PrimarySchool` for some reason what is built is office with whole building space type. Now to figure out why PrimarySchool isn't being used as argument. This is for rotation_45_party_wall_fraction

The warnings for the other two tests are `Not modeling core and perimeter zones for some portion of the model.` Below is log on 3.8.0 with standards 0.6.0 Notice how it is adding an office despite the fact that the argument for bldg_type_a is Secondary School

**MEASURE APPLICABILITY**
[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
0 = Success
**INITIAL CONDITION**
**FINAL CONDITION**
**INFO MESSAGES**
The building started with 0 spaces.
Creating bar based on space ratios from SmallOffice for building form defaults.
0.0 value for aspect ratio will be replaced with smart default for SmallOffice of 1.5.
0.0 value for minimum perimeter multiplier will be replaced with smart default for SmallOffice of 1.0.
0.0 value for floor height will be replaced with smart default for SmallOffice of 10.0.
0.0 value for window to wall ratio will be replaced with smart default for SmallOffice of 0.15.
The building started with 0 spaces.
Creating Space Types for SmallOffice.
Using OpenStudio Standards version 0.6.0 with template 90.1-2013.
Loading OpenStudio Standards data for 90.1-2013
Making bar with length of 122 ft and width of 82 ft
Intersection of 'Surface 4' with 'Surface 20' results in (Surface 4), (Surface 20),
Intersection of 'Surface 38' with 'Surface 22' results in (Surface 38), (Surface 22),
Intersection of 'Surface 21' with 'Surface 29' results in (Surface 21), (Surface 29),
Intersection of 'Surface 3' with 'Surface 11' results in (Surface 3), (Surface 11),
Intersection of 'Surface 39' with 'Surface 47' results in (Surface 39), (Surface 47),
Intersection of 'Surface 10' with 'Surface 26' results in (Surface 10), (Surface 26),
Intersection of 'Surface 44' with 'Surface 28' results in (Surface 44), (Surface 28),
Intersection of 'Surface 35' with 'Surface 27' results in (Surface 35), (Surface 27),
Intersection of 'Surface 17' with 'Surface 9' results in (Surface 17), (Surface 9),
Intersection of 'Surface 53' with 'Surface 45' results in (Surface 53), (Surface 45),
Intersection of 'Surface 16' with 'Surface 32' results in (Surface 16), (Surface 32),
Intersection of 'Surface 50' with 'Surface 34' results in (Surface 50), (Surface 34),
Intersecting and matching surfaces in story Story ground, this will create additional geometry.
Finding non-exterior walls and setting boundary condition to adiabatic
Created bar envelope with floor area of 10,000 ft^2. Total building area is 10,000 ft^2.
wall_area_ip: 4082.482904638622 ft^2
ns_wall_area_ip: 2449.4897427831743 ft^2
ew_wall_area_ip: 1632.9931618554479 ft^2
floor_area_to_perim_ratio: 7.466044736003113
bar_width: 81.6496580927726 ft
The building finished with 9 spaces.
**WARNING MESSAGES**
**ERROR MESSAGES**
***Machine-Readable Attributes**
[
{
   "name" : "bldg_type_a",
   "value" : "SecondarySchool"
},{

**Comment by DavidGoldwasser** [comment]
- [ ] Very heavy logging of this would be nice to remove
`Intersection of 'Surface 93' with 'Surface 101' results in (Surface 93), (Surface 101),`

**Comment by mdahlhausen** [comment]
Fixed with #195
