### ISSUE TITLE
Postprocessing failure summary file only includes last measure 

### ISSUE THREAD

**Issue by ChristopherCaradonna** [NatLabRockies/ComStock#234]
The failure summary created during postprocessing only includes the baseline and 1 upgrade (the last one processed), regardless of the number of upgrades. This is because the files are created individually per measure, with the same name and file path, so they overwrite each other.

We want a single file to be produced with the failure summary for the baseline and all upgrades. This is preferred over individual files per upgrade so that a user doesn't have to open potentially dozens of files to understand the run failures.

**Comment by wenyikuang** [comment]
Fixed this issue, but I think there is somethign wrong in the meta data check. Could we have a meeting to run a sample?

Thanks,
