### ISSUE TITLE
postproc dependency conflict

### ISSUE THREAD

**Issue by mdahlhausen** [NatLabRockies/ComStock#26]
creating a fresh conda environment and running `pip install -e .[dev]` in comstockpostproc results in this dependency conflict warning:

`awscli 1.29.74 requires colorama<0.4.5,>=0.2.5, but you have colorama 0.4.6 which is incompatible.`

switching to colorama 0.4.4 to resolve this warning produces a new warning:

`buildstock-query 2022.10.8 requires colorama>=0.4.5, but you have colorama 0.4.4 which is incompatible.`

The dependencies require a colorama <0.4.5 and >= 0.4.5, which is not possible.

**Comment by asparke2** [comment]
Could not replicate this when creating a fresh conda environment following the README instructions. The dependency requiring the conflicting colorama dependency is aws-cli, which isn't in the new environment after a successful installation, so maybe there was something leftover in a previous environment that caused this. Either way, it appears that buildstock-query can also remove its colorama dependency.
