### ISSUE TITLE
Is it possible to provide a example project similar as ResStock for user to run?

### ISSUE THREAD

**Issue by Kecheng-Chen** [NatLabRockies/ComStock#8]
I previously ran example projects provided by the ResStock locally with BuildStock Batch.  The website of BuildStock Batch also mentions that this tool can be used to run the ComStock project. Just curious about the possibility of providing example projects. Thanks in advance.

**Comment by tomaszG247** [comment]
Hello, I second this request. It would be very useful to have a working example, even if it does not demonstrate the full functionality of COMStock. I would expect a minimal example could be simply building one model, populating it with what is required, and report. I am not really familiar with ruby bindings so I will try to build a Openstudio workflow example, but having any running example would be much better. I understand that the rep is not supported currnetly but I expect you must have a running example somewhere

**Comment by mdahlhausen** [comment]
See the [ComStock Local Run README](https://github.com/NREL/ComStock/blob/main/comstock_local_run.md) for directions on doing a simple local run.
