### ISSUE TITLE
Fix segmentation name and logic for food service

### ISSUE THREAD

**Issue by asparke2** [NatLabRockies/ComStock#86]
Currently, all RetailStripMall buildings (even those with no food service component) are [being assigned](https://github.com/NREL/ComStock/blob/main/postprocessing/comstockpostproc/comstock.py#L728) to the [B: Food-Service, Freestanding and in Strip Malls with Small Packaged Units](https://github.com/NREL/ComStock/blob/main/postprocessing/comstockpostproc/naming_mixin.py#L190).

1. Assign any RetailStripMall buildings with no restaurant component to the "
2. Rename the `"B: Food-Service, Freestanding and in Strip Malls with Small Packaged Units"` to `"B: Buildings with Some Food-Service, Freestanding and in Strip Malls with Small Packaged Units"`

So the resulting two segments would be:
```
SEG_A = 'A: Non Food-Service Buildings with Small Packaged Units'
SEG_B = 'B: Buildings with Some Food-Service, Freestanding and in Strip Malls with Small Packaged Units'
```

**Comment by asparke2** [comment]
@mdahlhausen what do you think about the proposed change here to address the issue you identified with the phase II segmentation?

**Comment by mdahlhausen** [comment]
I don't like it; I think it is confusing to lump restaurants together with a significant amount of retail. A less than ideal but workable solution is to make 3 segments: 1) retail with no food service, 2) strip malls with some food service, and 3) stand-alone restaurants.

**Comment by asparke2** [comment]
Solution determined during team discussion:
1. All strip-malls with packaged units and 0% restaurant go into the `Non Food-Service Buildings with Small Packaged Units` segment.
2. The previous `Food-Service, Freestanding and in Strip Malls with Small Packaged Units` segment is renamed `Food-Service Buildings with Small Packaged Units` to indicate that it contains buildings that are 100% food service.
3. All strip-malls with >0% restaurant go into their own, new `Strip Malls with some Food-Service with Small Packaged Units` segment to indicate buildings that are a mix of food-service and non-food-service tenants. Although the upgrades applicable to this segment will look like a mash-up of the first two segments, the savings per floor area for any given upgrade (for example, a cooking equipment retrofit) will be lower because the retrofit will only apply to some of the tenant spaces in the building.
